# Generated by Django 5.0.6 on 2024-06-08 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_tutor_training_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='semaine_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
