# Generated by Django 5.0.6 on 2024-06-02 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_schedule_week_tutoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='availability',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
