# Generated by Django 5.0.6 on 2024-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_schedule_training_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='requires_response',
            field=models.BooleanField(default=False),
        ),
    ]
