# Generated by Django 5.0.6 on 2024-06-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message_requires_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='schedule_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='base.schedule'),
        ),
        migrations.AddField(
            model_name='message',
            name='schedule_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='base.schedule'),
        ),
    ]
